package com.soprasteria.aibydesign.codesentinel;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/** Writes one consolidated report for a multi-file review. */
public class ProjectReportGenerator {

    public void write(List<Path> files, Map<String, SquadResult> results,
                      String projectAnalysis, Path outputRoot) throws IOException {
        Files.createDirectories(outputRoot);

        long critical = count(results, Finding.Severity.CRITICAL);
        long major = count(results, Finding.Severity.MAJOR);
        long minor = count(results, Finding.Severity.MINOR);
        long recurring = results.values().stream()
                .mapToLong(r -> r.recurringFindings.size()).sum();
        int score = calculateScore(critical, major, minor, recurring);

        StringBuilder sb = new StringBuilder();
        sb.append("# CodeSentinel Squad — Project Review\n\n")
          .append("> Multi-file review with deterministic evidence, specialist agents, ")
          .append("critic validation, review memory and project-level integration analysis.\n\n");

        sb.append("## Quality Gate\n\n")
          .append("| Metric | Result |\n|---|---:|\n")
          .append("| Files reviewed | ").append(files.size()).append(" |\n")
          .append("| Critical findings | ").append(critical).append(" |\n")
          .append("| Major findings | ").append(major).append(" |\n")
          .append("| Minor findings | ").append(minor).append(" |\n")
          .append("| Recurring findings | ").append(recurring).append(" |\n")
          .append("| **Review score** | **").append(score).append("/100** |\n\n")
          .append(critical == 0 && score >= 80
                  ? "> **Gate: PASS WITH REVIEW** — no critical findings were detected by deterministic analysis.\n\n"
                  : "> **Gate: ACTION REQUIRED** — resolve critical/major findings before treating this review as clean.\n\n");

        sb.append("## File Status\n\n")
          .append("| File | Language | Findings | Recurring | AI status |\n|---|---|---:|---:|---|\n");
        results.forEach((name, r) -> sb.append("| `").append(name).append("` | ")
                .append(LanguageDetector.detect(Path.of(name)).displayName()).append(" | ")
                .append(r.findings.size()).append(" | ")
                .append(r.recurringFindings.size()).append(" | ")
                .append(r.safeMode ? "Safe Mode" : "AI review").append(" |\n"));
        sb.append("\n");

        sb.append("## Project Integration Review\n\n")
          .append(projectAnalysis).append("\n\n")
          .append("## Trust Model\n\n")
          .append("Deterministic findings are evidence, not proof. Specialist outputs are recommendations. ")
          .append("The Project Integration Agent performs a second pass across file and language boundaries. ")
          .append("Human approval remains the final quality gate.\n\n")
          .append("---\n_Generated by CodeSentinel Squad._\n");

        Files.writeString(outputRoot.resolve("project-review.md"), sb.toString());
    }

    private long count(Map<String, SquadResult> results, Finding.Severity severity) {
        return results.values().stream().flatMap(r -> r.findings.stream())
                .filter(f -> f.getSeverity() == severity).count();
    }

    static int calculateScore(long critical, long major, long minor, long recurring) {
        int score = 100;
        score -= Math.min(60, (int) critical * 20);
        score -= Math.min(25, (int) major * 7);
        score -= Math.min(10, (int) minor * 2);
        score -= Math.min(10, (int) recurring * 2);
        return Math.max(0, score);
    }
}
