package com.soprasteria.aibydesign.codesentinel;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * Creates the consolidated report for a multi-file review.
 */
public class ProjectReportGenerator {

    public void write(
            List<Path> files,
            Map<String, SquadResult> results,
            String projectAnalysis,
            Path outputRoot) throws IOException {

        Files.createDirectories(outputRoot);

        long critical = count(results, Finding.Severity.CRITICAL);
        long major = count(results, Finding.Severity.MAJOR);
        long minor = count(results, Finding.Severity.MINOR);

        long recurring = results.values().stream()
                .mapToLong(result -> result.recurringFindings.size())
                .sum();

        int score = calculateScore(
                critical,
                major,
                minor,
                recurring
        );

        StringBuilder report = new StringBuilder();

        report.append("# CodeSentinel Squad — Project Review\n\n")
                .append("> Consolidated review of multiple files using deterministic analysis, ")
                .append("specialist agents, review memory and project-level integration checks.\n\n");

        appendQualityGate(
                report,
                results.size(),
                critical,
                major,
                minor,
                recurring,
                score
        );

        appendFileStatus(report, results);

        report.append("## Project Integration Review\n\n")
                .append(projectAnalysis)
                .append("\n\n");

        report.append("## Trust Model\n\n")
                .append("Deterministic findings provide the initial evidence. ")
                .append("Specialist agents add recommendations based on that evidence. ")
                .append("The Project Integration Agent then looks across files and languages ")
                .append("for issues that may not be visible in an individual file. ")
                .append("The final decision remains with the developer or reviewer.\n\n");

        report.append("---\n")
                .append("_Generated by CodeSentinel Squad._\n");

        Files.writeString(
                outputRoot.resolve("project-review.md"),
                report.toString()
        );
    }

    private void appendQualityGate(
            StringBuilder report,
            int filesReviewed,
            long critical,
            long major,
            long minor,
            long recurring,
            int score) {

        report.append("## Quality Gate\n\n")
                .append("| Metric | Result |\n")
                .append("|---|---:|\n")
                .append("| Files reviewed | ")
                .append(filesReviewed)
                .append(" |\n")
                .append("| Critical findings | ")
                .append(critical)
                .append(" |\n")
                .append("| Major findings | ")
                .append(major)
                .append(" |\n")
                .append("| Minor findings | ")
                .append(minor)
                .append(" |\n")
                .append("| Recurring findings | ")
                .append(recurring)
                .append(" |\n")
                .append("| **Review score** | **")
                .append(score)
                .append("/100** |\n\n");

        if (critical == 0 && score >= 80) {
            report.append(
                    "> **Gate: PASS WITH REVIEW** — no critical findings "
                            + "were detected by deterministic analysis.\n\n"
            );
        } else {
            report.append(
                    "> **Gate: ACTION REQUIRED** — review the critical and "
                            + "major findings before considering the change clean.\n\n"
            );
        }
    }

    private void appendFileStatus(
            StringBuilder report,
            Map<String, SquadResult> results) {

        report.append("## File Status\n\n")
                .append("| File | Language | Findings | Recurring | Review mode |\n")
                .append("|---|---|---:|---:|---|\n");

        results.forEach((fileName, result) -> {

            Path path = Path.of(fileName);
            Language language = LanguageDetector.detect(path);

            report.append("| `")
                    .append(fileName)
                    .append("` | ")
                    .append(language.displayName())
                    .append(" | ")
                    .append(result.findings.size())
                    .append(" | ")
                    .append(result.recurringFindings.size())
                    .append(" | ")
                    .append(result.safeMode ? "Safe Mode" : "AI review")
                    .append(" |\n");
        });

        report.append("\n");
    }

    private long count(
            Map<String, SquadResult> results,
            Finding.Severity severity) {

        return results.values().stream()
                .flatMap(result -> result.findings.stream())
                .filter(finding -> finding.getSeverity() == severity)
                .count();
    }

    static int calculateScore(
            long critical,
            long major,
            long minor,
            long recurring) {

        int score = 100;

        score -= Math.min(60, (int) critical * 20);
        score -= Math.min(25, (int) major * 7);
        score -= Math.min(10, (int) minor * 2);
        score -= Math.min(10, (int) recurring * 2);

        return Math.max(0, score);
    }
}