package com.soprasteria.aibydesign.codesentinel;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Holds the result of a complete CodeSentinel review.
 */
public class SquadResult {

    // Findings produced by the deterministic static analyzer.
    public List<Finding> findings = new ArrayList<>();

    // Findings whose same category + description appeared in memory.
    public List<Finding> recurringFindings = new ArrayList<>();

    // True when the AI service is not configured.
    // Static analysis still works in this mode.
    public boolean safeMode = false;

    // True when the generated tests passed the Critic review.
    public boolean testsApproved = false;

    // Agents that were actually executed.
    public List<String> dispatchedAgents = new ArrayList<>();

    // Agents that were considered but skipped.
    public List<String> skippedAgents = new ArrayList<>();

    // Conversation/history between Test Agent and Critic.
    public List<String> criticTranscript = new ArrayList<>();

    // Output generated by each specialist agent.
    public Map<String, String> agentOutputs =
            new LinkedHashMap<>();

    // Non-fatal problems during the review.
    // An individual agent failure should not stop the complete review.
    public List<String> warnings = new ArrayList<>();
}