import java.util.List;
import java.util.regex.Pattern;

/**
 * Reviews the tests generated by the Test Agent.
 *
 * The Critic has two simple checks:
 *
 * 1. Structural check - performed locally without an AI call.
 * 2. Semantic check - asks the AI reviewer whether the tests actually
 *    address the findings.
 *
 * The Critic does not claim that the generated tests were compiled.
 * Compilation verification can be added later as a separate step.
 */
public class CriticAgent {

    private static final Pattern TEST_PATTERN =
            Pattern.compile("@Test");

    private static final Pattern CLASS_PATTERN =
            Pattern.compile("class\\s+\\w+");

    private static final Pattern ASSERTION_PATTERN =
            Pattern.compile(
                    "assert[A-Za-z0-9_]*\\s*\\("
                            + "|verify\\s*\\(");

    public static class Verdict {

        public final boolean approved;
        public final String feedback;

        Verdict(boolean approved, String feedback) {
            this.approved = approved;
            this.feedback = feedback;
        }
    }

    /**
     * Performs cheap local checks before using an AI review call.
     */
    public Verdict structuralCheck(String generatedTestCode) {

        if (generatedTestCode == null
                || generatedTestCode.isBlank()) {

            return new Verdict(
                    false,
                    "Empty output - no test code was generated.");
        }

        if (!TEST_PATTERN.matcher(generatedTestCode).find()) {

            return new Verdict(
                    false,
                    "No @Test method found - this is not a usable JUnit test class.");
        }

        if (!CLASS_PATTERN.matcher(generatedTestCode).find()) {

            return new Verdict(
                    false,
                    "No class declaration found - output does not look like a complete Java file.");
        }

        if (!containsMeaningfulAssertion(generatedTestCode)) {

            return new Verdict(
                    false,
                    "No meaningful assertion or Mockito verify() was found. "
                            + "The generated tests should verify expected behaviour.");
        }

        long openBraces =
                generatedTestCode.chars()
                        .filter(c -> c == '{')
                        .count();

        long closeBraces =
                generatedTestCode.chars()
                        .filter(c -> c == '}')
                        .count();

        if (openBraces != closeBraces) {

            return new Verdict(
                    false,
                    "Unbalanced braces ("
                            + openBraces
                            + " open vs "
                            + closeBraces
                            + " close). "
                            + "The generated file may be incomplete.");
        }

        return new Verdict(
                true,
                "Structural check passed.");
    }

    /**
     * Checks whether the generated tests contain an actual assertion.
     */
    private boolean containsMeaningfulAssertion(String code) {

        return ASSERTION_PATTERN
                .matcher(code)
                .find();
    }

    /**
     * Performs the semantic review using the configured AI client.
     */
    public Verdict semanticCheck(
            String generatedTestCode,
            List<Finding> findings,
            ClaudeClient client) throws Exception {

        String system =
                "You are a strict senior QA reviewer. "
                        + "Review the generated JUnit tests against the reported issues. "
                        + "Approve only when the tests meaningfully exercise the issues. "
                        + "Do not approve just because the code looks syntactically correct. "
                        + "Reply with exactly one line: "
                        + "'APPROVED' or 'REVISE: <short reason>'.";

        StringBuilder user = new StringBuilder();

        user.append("Issues the tests were supposed to cover:\n");

        for (Finding finding : findings) {
            user.append("- ")
                    .append(finding)
                    .append("\n");
        }

        user.append("\nGenerated test code:\n")
                .append(generatedTestCode);

        String response =
                client.ask(
                        system,
                        user.toString()).trim();

        if (response.toUpperCase().startsWith("APPROVED")) {
            return new Verdict(true, response);
        }

        return new Verdict(false, response);
    }
}