import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

/**
 * Creates the final CodeSentinel review report.
 *
 * The report contains:
 * - review summary
 * - findings
 * - recurring findings
 * - agent activity
 * - agent output
 * - Critic/Test loop
 * - warnings
 */
public class ReportGenerator {

    public void writeAll(
            String className,
            SquadResult result,
            Path outputDir) throws IOException {

        Files.createDirectories(outputDir);

        writeReviewMarkdown(
                className,
                result,
                outputDir);

        String testOutput =
                result.agentOutputs.get("Test Generation Agent");

        if (testOutput != null && !testOutput.isBlank()) {

            Files.writeString(
                    outputDir.resolve(className + "Test.java"),
                    testOutput);
        }

        String docsOutput =
                result.agentOutputs.get("Documentation Agent");

        if (docsOutput != null && !docsOutput.isBlank()) {

            int idx =
                    docsOutput.indexOf("PLAIN_SUMMARY:");

            String source =
                    idx >= 0
                            ? docsOutput.substring(0, idx).trim()
                            : docsOutput;

            Files.writeString(
                    outputDir.resolve(className + ".java"),
                    source);
        }
    }

    private void writeReviewMarkdown(
            String className,
            SquadResult result,
            Path outputDir) throws IOException {

        StringBuilder sb = new StringBuilder();

        sb.append("# CodeSentinel Squad Review — ")
                .append(className)
                .append(".java\n\n");

        writeSummary(sb, result);

        if (result.safeMode) {

            sb.append("> **Safe Mode:** `ANTHROPIC_API_KEY` is not configured. ")
                    .append("Static analysis was completed without AI agents.\n\n");

        } else {

            sb.append("## Agent Activity\n\n");

            sb.append("**Dispatched:** ")
                    .append(result.dispatchedAgents.isEmpty()
                            ? "none"
                            : String.join(
                            ", ",
                            result.dispatchedAgents))
                    .append("\n\n");

            sb.append("**Skipped:** ")
                    .append(result.skippedAgents.isEmpty()
                            ? "none"
                            : String.join(
                            ", ",
                            result.skippedAgents))
                    .append("\n\n");
        }

        writeWarnings(sb, result);

        writeRecurringFindings(sb, result);

        writeFindings(sb, result);

        writeAgentOutputs(sb, result);

        writeCriticTranscript(sb, result);

        sb.append("---\n")
                .append("_Generated by the CodeSentinel multi-agent squad._\n");

        Files.writeString(
                outputDir.resolve("review.md"),
                sb.toString());
    }

    private void writeSummary(
            StringBuilder sb,
            SquadResult result) {

        long critical =
                countBySeverity(
                        result,
                        Finding.Severity.CRITICAL);

        long major =
                countBySeverity(
                        result,
                        Finding.Severity.MAJOR);

        long minor =
                countBySeverity(
                        result,
                        Finding.Severity.MINOR);

        sb.append("## Review Summary\n\n");

        sb.append("| Metric | Count |\n");
        sb.append("|---|---:|\n");
        sb.append("| Total findings | ")
                .append(result.findings.size())
                .append(" |\n");

        sb.append("| Critical | ")
                .append(critical)
                .append(" |\n");

        sb.append("| Major | ")
                .append(major)
                .append(" |\n");

        sb.append("| Minor | ")
                .append(minor)
                .append(" |\n");

        sb.append("| Recurring findings | ")
                .append(result.recurringFindings.size())
                .append(" |\n");

        sb.append("| Agents dispatched | ")
                .append(result.dispatchedAgents.size())
                .append(" |\n");

        sb.append("| Agents skipped | ")
                .append(result.skippedAgents.size())
                .append(" |\n");

        sb.append("\n");
    }

    private long countBySeverity(
            SquadResult result,
            Finding.Severity severity) {

        return result.findings.stream()
                .filter(f -> f.getSeverity() == severity)
                .count();
    }

    private void writeWarnings(
            StringBuilder sb,
            SquadResult result) {

        if (result.warnings.isEmpty()) {
            return;
        }

        sb.append("## Warnings\n\n");

        for (String warning : result.warnings) {
            sb.append("- ")
                    .append(warning)
                    .append("\n");
        }

        sb.append("\n");
    }

    private void writeRecurringFindings(
            StringBuilder sb,
            SquadResult result) {

        if (result.recurringFindings.isEmpty()) {
            return;
        }

        sb.append("## Recurring Issues\n\n");

        sb.append(
                "These issue signatures were detected in a previous "
                        + "review and detected again in the current review.\n\n");

        for (Finding finding : result.recurringFindings) {

            sb.append("- Line ")
                    .append(finding.getLineNumber())
                    .append(" [")
                    .append(finding.getCategory())
                    .append("]: ")
                    .append(finding.getDescription())
                    .append("\n");
        }

        sb.append("\n");
    }

    private void writeFindings(
            StringBuilder sb,
            SquadResult result) {

        for (Finding.Severity severity :
                List.of(
                        Finding.Severity.CRITICAL,
                        Finding.Severity.MAJOR,
                        Finding.Severity.MINOR)) {

            List<Finding> group =
                    result.findings.stream()
                            .filter(f ->
                                    f.getSeverity() == severity)
                            .sorted(
                                    Comparator.comparingInt(
                                            Finding::getLineNumber))
                            .toList();

            if (group.isEmpty()) {
                continue;
            }

            sb.append("## ")
                    .append(capitalize(severity.name()))
                    .append("\n\n");

            for (Finding finding : group) {

                sb.append("- Line ")
                        .append(finding.getLineNumber())
                        .append(" [")
                        .append(finding.getCategory())
                        .append("]: ")
                        .append(finding.getDescription())
                        .append("\n");
            }

            sb.append("\n");
        }
    }

    private void writeAgentOutputs(
            StringBuilder sb,
            SquadResult result) {

        for (Map.Entry<String, String> entry :
                result.agentOutputs.entrySet()) {

            if ("Test Generation Agent"
                    .equals(entry.getKey())) {

                continue;
            }

            sb.append("## ")
                    .append(entry.getKey())
                    .append(" Output\n\n");

            sb.append(entry.getValue())
                    .append("\n\n");
        }
    }

    private void writeCriticTranscript(
            StringBuilder sb,
            SquadResult result) {

        if (result.criticTranscript.isEmpty()) {
            return;
        }

        sb.append("## Critic / Reflection Loop\n\n");

        for (String line :
                result.criticTranscript) {

            sb.append("- ")
                    .append(line)
                    .append("\n");
        }

        if (result.testsApproved) {

            sb.append(
                    "\n**Final result:** Tests were approved by "
                            + "the Critic Agent.\n");

        } else {

            sb.append(
                    "\n**Final result:** Tests were not fully approved. "
                            + "Human review is recommended.\n");
        }

        sb.append("\n");
    }

    private String capitalize(String value) {

        if (value == null || value.isBlank()) {
            return value;
        }

        return value.charAt(0)
                + value.substring(1).toLowerCase();
    }
}